### ISSUE TITLE
Multilib Support

### ISSUE THREAD

**Issue by JesusMcCloud** [KoKuToru/koku-xinput-wine#2]
Is there a way to get it to work with multilib wine on a 32 bit wineprefix?

**Comment by mixedCase** [comment]
I'm getting `(wrong ELF class: ELFCLASS32)` when running on a win32 wineprefix.

**Comment by KoKuToru** [comment]
sounds right, on a 64bit system.

`LD_PRELOAD` will preload the shared library into any following process, it doesn't matter if it's 64bit or 32bit.. 
If you add a 32bit shared library and a 64bit application gets started, you will get this error message. 

So as long as you shared library is 32bit and your wine process is 32bit, everything is fine

**Comment by mixedCase** [comment]
How can I make sure wine runs in 32 bit mode? I'm running wine-staging from the Arch repos, tried with wine as well but no dice.

**Comment by KoKuToru** [comment]
There is no need to "make sure", `wine` can't execute 64bit windows applications.
But you still will see the error message from what ever gets loaded before/after/while `wine` loads your 32bit windows application.

**Comment by mixedCase** [comment]
Wine is certainly able to run 64 bit windows applications.

In any case, I misunderstood the purpose of this application and was trying to use it to force windows applications into using xinput mode instead of dinput by default. Thank you for your time.
