### ISSUE TITLE
compilation instructions failed

### ISSUE THREAD

**Issue by lozbrown** [KoKuToru/koku-xinput-wine#3]

**Comment by lozbrown** [comment]
loz@gravity:~/koku-xinput-wine$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/loz/koku-xinput-wine
loz@gravity:~/koku-xinput-wine$ make
[ 25%] Building CXX object CMakeFiles/koku-xinput-wine.dir/main.cpp.o
In file included from /home/loz/koku-xinput-wine/main.cpp:2:0:
/usr/include/c++/4.9/string:38:28: fatal error: bits/c++config.h: No such file or directory
 #include <bits/c++config.h>
                            ^
compilation terminated.
CMakeFiles/koku-xinput-wine.dir/build.make:54: recipe for target 'CMakeFiles/koku-xinput-wine.dir/main.cpp.o' failed
make[2]: *** [CMakeFiles/koku-xinput-wine.dir/main.cpp.o] Error 1
CMakeFiles/Makefile2:60: recipe for target 'CMakeFiles/koku-xinput-wine.dir/all' failed
make[1]: *** [CMakeFiles/koku-xinput-wine.dir/all] Error 2
Makefile:76: recipe for target 'all' failed
make: *** [all] Error 2
loz@gravity:~/koku-xinput-wine$

**Comment by KoKuToru** [comment]
What linux-distribution are you using ?
This error message sounds like your build environment is broken.

**Comment by lozbrown** [comment]
Ubuntu vivid so it's a 3.19 kernel its 64 bit but should support multi
arch. All packages are standard from repos, I haven't complied anything
else myself.

Anything I should check?

I'm hoping to be able to use this to control GTA IV with my sony sixaxis
controllers

**Comment by KoKuToru** [comment]
I can confirm that it wont work on "Ubuntu Vivid" (Virtual Box).
Ubunuts `gcc-multilib` is broken.
It can't even compile

```
#include <string>
#include <iostream>

int main() {
    std::string test = "Hello World";
    std::cout << test << std::endl;
}
```
with `g++ -m32 test.cpp`...

Because I am not an Ubunut-User, I have no idea how to force it to use a different `g++` version...

**Comment by jprjr** [comment]
@lozbrown @KoKuToru You need the g++-multilib package

**Comment by KoKuToru** [comment]
Yeah `g++-multilib` does work, no idea why I didn't tried this package last time.. (I am not an ubuntu user)

ArchLinux only has `gcc-multilib` which also works for C++
