### ISSUE TITLE
[Request] PLEASE provide a koku-xinput-wine.so download

### ISSUE THREAD

**Issue by markubiak** [KoKuToru/koku-xinput-wine#4]
Hi there,
     I'm just trying to get my controller to work in Rocket League.  It's been nearly impossible to compile your lib on either Arch Linux or Fedora 23, I still haven't been able to get it to work on either one.  It keeps complaining that my SDL2 lib is the "wrong version".  Either way, most users don't know how to compile things or want to (I have done some programming in C and still find this difficult).  If you could provide a precompiled 32 bit version of the library available for download, that would be awesome.  Bonus points if you can provide complete example configurations for controllers.

**Comment by KoKuToru** [comment]
Sorry but it builds here.
The default configuration uses SDL not SDL2, did you change the `CMakeLists.txt` ?

> Either way, most users don't know how to compile things or want to..

These people should **not** use this library.
This library is a ugly hack done for users who understand how to use and or know how to code.
This library is not a simple plug and play. You might need to tweak the code to get it working for
certain games !

> if you can provide complete example configurations for controllers.

Configuration is auto generated at first usage

> If you could provide a precompiled 32 bit version of the library available for download

Sorry not possible, linux does update often and libraries can change on daily basis.
It's not simple to release a binary version which would work for days/months/years (or different distribution)
